### Read all pizzas with File variable
@baseUrl = http://localhost:3000

GET {{baseUrl}}/films



### Create a pizza
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title": "Ok",
    "duration": 100,
    "budget":"1000m",
    "link": "OkOk"
}



